---
- name: Add aliases for host
  ansible.builtin.template:
    src: aliases.j2
    dest: /etc/aliases
    mode: '0644'
    owner: root
    group: root
  with_items:
    - "{{ postfix_aliases }}"
  notify:
    - Update aliases
    - Restart postfix service
